language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t jhearington/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jhearington/react-test npm test

after_success:
  - docker build -t jhearington/multi-client ./client
  - docker build -t jhearington/multi-nginx ./nginx
  - docker build -t jhearington/multi-server ./server
  - docker build -t jhearington/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jhearington/multi-client
  - docker push jhearington/multi-nginx
  - docker push jhearington/multi-server
  - docker push jhearington/multi-worker


deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-035222141193
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY