language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t jhearington/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jhearington/react-test npm test

after_success:
  - docker build -t jhearington87/multi-client ./client
  - docker build -t jhearington87/multi-nginx ./multi-nginx
  - docker built -t jhearington87/multi-server ./server
  - docker built -t jhearington87/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jhearington87/multi-client
  - docker push jhearington87/multi-nginx
  - docker push jhearington87/multi-server
  - docker push jhearington87/multi-worker
